#!/usr/bin/env bash


export KAFKA_HOME=/appvol/ilovemyhome/runtime/kafka

## generated by $KAFKA_HOME/bin/kafka-storage.sh random-uuid
export KAFKA_CLUSTER_ID="L6p9ujnZRouvFjkgECSZsQ"

## Need to init the store first
$KAFKA_HOME/bin/kafka-storage.sh format \
--config $KAFKA_HOME/config/server.properties \
--cluster-id $KAFKA_CLUSTER_ID  \
--ignore-formatted \
--initial-controllers 1@kf30.jack007.top:9093:JEXY6aqzQY-32P5TStzaFg,2@kf31.jack007.top:9093:MvDxzVmcRsaTz33bUuRU6A,3@kf32.jack007.top:9093:07R5amHmR32VDA6jHkGbTA


$KAFKA_HOME/bin/kafka-server-start.sh $KAFKA_HOME/config/server.properties

